### ISSUE TITLE
Do you test your approach on other languages?

### ISSUE THREAD

**Issue by hadifar** [Leonard-Xu/CWE#3]
I want to implement same thing (positional model) in **English**. Did you test this case? If yes, Did your results were significant?

thanks, Amir

**Comment by Leonard-Xu** [comment]
I did not try that. But I think this model is unlikely to work in English because English has only 26 characters. 

Rather than simply adding up all character vectors in English, adding up vectors of affixes or composing characters using convolutional neural networks (CNN) may be a better approach.

Thanks, 
Lei
